language: rust
rust:
  - stable
  - beta
  - nightly
  # Minimum supported Rust version.
  # Please also change README.md if you change this.
  - 1.17.0
matrix:
  allow_failures:
    - rust: nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose --no-default-features --features="num-bigint bit-vec chrono"
  - cargo doc --features="num-bigint bit-vec chrono"
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  ssh-agent .travis/deploy.sh
notifications:
  email:
    on_success: never
