name: test

on: [push, pull_request]

env:
  # Minimum supported Rust version.
  # Please also change README.md if you change this.
  MSRV: 1.36.0

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
        - stable
        - beta
        - nightly
        - msrv

    env:
      RUSTFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust == 'msrv' && env.MSRV || matrix.rust }}
        override: true
    - name: Test
      run: |
        cargo build --verbose
        cargo test --verbose --no-default-features

        # don't test features on MSRV
        if [[ '${{ matrix.rust }}' != 'msrv' ]]; then
          cargo test --verbose --no-default-features --features="num-bigint bit-vec time std"
          cargo doc --features="num-bigint bit-vec time"
        else
          cargo doc
        fi
      continue-on-error: ${{ matrix.rust == 'nightly' }}
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        force_orphan: true
      if: github.ref == 'refs/heads/master' && matrix.rust == 'stable'
